"""empty message

Revision ID: 515d5a15c72c
Revises: c0b151bf5254
Create Date: 2023-09-12 20:06:19.131390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '515d5a15c72c'
down_revision: Union[str, None] = 'c0b151bf5254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_roles', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('employee_roles', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_roles', 'updated_at')
    op.drop_column('employee_roles', 'created_at')
    # ### end Alembic commands ###
