"""empty message

Revision ID: 99db3e0030ea
Revises: 515d5a15c72c
Create Date: 2023-09-12 20:07:36.146836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99db3e0030ea'
down_revision: Union[str, None] = '515d5a15c72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_roles', 'created_at')
    op.drop_column('employee_roles', 'updated_at')
    op.add_column('employees', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('employees', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'created_at')
    op.add_column('employee_roles', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('employee_roles', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
