"""empty message

Revision ID: c0b151bf5254
Revises: 4641ea3a9814
Create Date: 2023-09-12 20:00:58.714864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b151bf5254'
down_revision: Union[str, None] = '4641ea3a9814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('phone_number', sa.String(length=512), nullable=False),
    sa.Column('employee_role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_role_id'], ['employee_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('employee_roles')
    # ### end Alembic commands ###
