# name: Code Analysis (pre-commit)
# on:
#   push:
#     branches: [main, develop]
#     paths:
#       - "**.py"
#       - "**.toml"
#       - "**.lock"
#   pull_request:
#     branches: [main]
#     types: [opened, synchronize]
#     paths:
#       - "**.py"
#       - "**.toml"
#       - "**.lock"

# jobs:
#   pre_commit:
#     strategy:
#       matrix:
#         python-version: ["3.10"]
#         poetry-version: ["1.6.1"]
#         os: [ubuntu-22.04]
#     runs-on: ${{ matrix.os }}
#     steps:
#       - name: Checkout a Git repo
#         uses: actions/checkout@v3
#       - name: Cache deps
#         uses: actions/cache@v1
#         with:
#           path: ~/.cache/pypoetry/
#           key: python-deps-${{ hashFiles('**/poetry.lock') }}
#       - name: Installing Python
#         uses: actions/setup-python@v4
#         with: 
#           python-version: ${{ matrix.python-version }}
#       - name: Installing Poetry
#         uses: abatilo/actions-poetry@v2
#         with: 
#           poetry-version: ${{ matrix.poetry-version }}
#       - name: Installing Deps
#         run: poetry install
#       - name: pre-commit
#         uses: pre-commit/action@v3.0.0
